# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.srcs/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0.xci
# IP: The module: 'astar_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.gen/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'astar_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.gen/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'astar_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.gen/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'astar_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.srcs/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0.xci
# IP: The module: 'astar_design_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.gen/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'astar_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.gen/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'astar_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.gen/sources_1/bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'astar_design_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
