# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/astar_design/astar_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design || ORIG_REF_NAME==astar_design} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_processing_system7_0_0/astar_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_processing_system7_0_0 || ORIG_REF_NAME==astar_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_axi_dma_0_0/astar_design_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_axi_dma_0_0 || ORIG_REF_NAME==astar_design_axi_dma_0_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_xlconcat_0_0/astar_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_xlconcat_0_0 || ORIG_REF_NAME==astar_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_auto_pc_0/astar_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_auto_pc_0 || ORIG_REF_NAME==astar_design_auto_pc_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_ps7_0_axi_periph_0/astar_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==astar_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_rst_ps7_0_100M_0/astar_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==astar_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_xbar_0/astar_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_xbar_0 || ORIG_REF_NAME==astar_design_xbar_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_auto_us_0/astar_design_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_auto_us_0 || ORIG_REF_NAME==astar_design_auto_us_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_auto_us_1/astar_design_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_auto_us_1 || ORIG_REF_NAME==astar_design_auto_us_1} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_auto_us_2/astar_design_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_auto_us_2 || ORIG_REF_NAME==astar_design_auto_us_2} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_auto_pc_1/astar_design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_auto_pc_1 || ORIG_REF_NAME==astar_design_auto_pc_1} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_axi_mem_intercon_0/astar_design_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_axi_mem_intercon_0 || ORIG_REF_NAME==astar_design_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/astar_design/ip/astar_design_astar_stream_0_0/astar_design_astar_stream_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==astar_design_astar_stream_0_0 || ORIG_REF_NAME==astar_design_astar_stream_0_0} -quiet] -quiet

# XDC: c:/Users/dawid/SDUP/astar_pathfinder_co-processor_on_fpga/astar/astar.gen/sources_1/bd/astar_design/astar_design_ooc.xdc
